

#######################################################
########## CHILDREN'S BASELINE VARIABLES  ########
######################################################


#------------- Upload the tagsets children_base.CHILDYA
# ------------ and mother_educ.CHILDYA to get access to the data
# ------------ used in this script
# ------------ Before running this script, you have to run the
# ------------ code automatically generated by NLS investigator
# ------------ that constructs the dataset.

############# TIME INVARIANT VARIABLES ##################

data$ID<-data$CPUBID_XRND
data$motherID<-data$MPUBID_XRND
data$race<-data$CRACE_XRND
data$sex<-data$CSEX_XRND
data$datebirth<-data$CYRB_XRND
data$birthorder<-data$BTHORDR_XRND
data$birthage<-data$MAGEBIR_XRND

############# TIME VARIANT VARIABLES ##################

################## DEP VARIABLES - PARENTING #####################

#### HOME PERCENTILE SCORES ####

data$homep_1986<-data$HOMEP1986_1986
data$homep_1988<-data$HOMEP1988_1988
data$homep_1990<-data$HOMEP1990_1990
data$homep_1992<-data$HOMEP1992_1992
data$homep_1994<-data$HOMEP1994_1994
data$homep_1996<-data$HOMEP1996_1996
data$homep_1998<-data$HOMEP1998_1998
data$homep_2000<-data$HOMEP2000_2000
data$homep_2002<-data$HOMEP2002_2002
data$homep_2004<-data$HOMEP2004_2004
data$homep_2006<-data$HOMEP2006_2006
data$homep_2008<-data$HOMEP2008_2008
data$homep_2010<-data$HOMEP2010_2010
data$homep_2012<-data$HOMEP2012_2012
data$homep_2014<-data$HOMEP2014_2014

#### HOME STANDARD SCORES ####

data$homez_1986<-data$HOMEZ1986_1986
data$homez_1988<-data$HOMEZ1988_1988
data$homez_1990<-data$HOMEZ1990_1990
data$homez_1992<-data$HOMEZ1992_1992
data$homez_1994<-data$HOMEZ1994_1994
data$homez_1996<-data$HOMEZ1996_1996
data$homez_1998<-data$HOMEZ1998_1998
data$homez_2000<-data$HOMEZ2000_2000
data$homez_2002<-data$HOMEZ2002_2002
data$homez_2004<-data$HOMEZ2004_2004
data$homez_2006<-data$HOMEZ2006_2006
data$homez_2008<-data$HOMEZ2008_2008
data$homez_2010<-data$HOMEZ2010_2010
data$homez_2012<-data$HOMEZ2012_2012
data$homez_2014<-data$HOMEZ2014_2014

#### COGNITIVE STIMULATION PERCENTILES ####

data$cognp_1986<-data$COGNP1986_1986
data$cognp_1988<-data$COGNP1988_1988
data$cognp_1990<-data$COGNP1990_1990
data$cognp_1992<-data$COGNP1992_1992
data$cognp_1994<-data$COGNP1994_1994
data$cognp_1996<-data$COGNP1996_1996
data$cognp_1998<-data$COGNP1998_1998
data$cognp_2000<-data$COGNP2000_2000
data$cognp_2002<-data$COGNP2002_2002
data$cognp_2004<-data$COGNP2004_2004
data$cognp_2006<-data$COGNP2006_2006
data$cognp_2008<-data$COGNP2008_2008
data$cognp_2010<-data$COGNP2010_2010
data$cognp_2012<-data$COGNP2012_2012
data$cognp_2014<-data$COGNP2014_2014

#### COGNITIVE STIMULATION STANDARD SCORES ###

data$cognz_1986<-data$COGNZ1986_1986
data$cognz_1988<-data$COGNZ1988_1988
data$cognz_1990<-data$COGNZ1990_1990
data$cognz_1992<-data$COGNZ1992_1992
data$cognz_1994<-data$COGNZ1994_1994
data$cognz_1996<-data$COGNZ1996_1996
data$cognz_1998<-data$COGNZ1998_1998
data$cognz_2000<-data$COGNZ2000_2000
data$cognz_2002<-data$COGNZ2002_2002
data$cognz_2004<-data$COGNZ2004_2004
data$cognz_2006<-data$COGNZ2006_2006
data$cognz_2008<-data$COGNZ2008_2008
data$cognz_2010<-data$COGNZ2010_2010
data$cognz_2012<-data$COGNZ2012_2012
data$cognz_2014<-data$COGNZ2014_2014

#### EMOTIONAL SUPPORT PERCENTILES ###

data$emotp_1986<-data$EMOTP1986_1986
data$emotp_1988<-data$EMOTP1988_1988
data$emotp_1990<-data$EMOTP1990_1990
data$emotp_1992<-data$EMOTP1992_1992
data$emotp_1994<-data$EMOTP1994_1994
data$emotp_1996<-data$EMOTP1996_1996
data$emotp_1998<-data$EMOTP1998_1998
data$emotp_2000<-data$EMOTP2000_2000
data$emotp_2002<-data$EMOTP2002_2002
data$emotp_2004<-data$EMOTP2004_2004
data$emotp_2006<-data$EMOTP2006_2006
data$emotp_2008<-data$EMOTP2008_2008
data$emotp_2010<-data$EMOTP2010_2010
data$emotp_2012<-data$EMOTP2012_2012
data$emotp_2014<-data$EMOTP2014_2014


### EMOTIONAL SUPPORT STANDARD SCORES ####

data$emotz_1986<-data$EMOTZ1986_1986
data$emotz_1988<-data$EMOTZ1988_1988
data$emotz_1990<-data$EMOTZ1990_1990
data$emotz_1992<-data$EMOTZ1992_1992
data$emotz_1994<-data$EMOTZ1994_1994
data$emotz_1996<-data$EMOTZ1996_1996
data$emotz_1998<-data$EMOTZ1998_1998
data$emotz_2000<-data$EMOTZ2000_2000
data$emotz_2002<-data$EMOTZ2002_2002
data$emotz_2004<-data$EMOTZ2004_2004
data$emotz_2006<-data$EMOTZ2006_2006
data$emotz_2008<-data$EMOTZ2008_2008
data$emotz_2010<-data$EMOTZ2010_2010
data$emotz_2012<-data$EMOTZ2012_2012
data$emotz_2014<-data$EMOTZ2014_2014

############## INDEPENDENT VAR  - CHILDREN PERFORMANCE ##############

############## MOTOR AND SOCIAL DEVELOPMENT STD SCORES ###############

data$motoz_1986<-data$MOTOZ1986_1986
data$motoz_1988<-data$MOTOZ1988_1988
data$motoz_1990<-data$MOTOZ1990_1990
data$motoz_1992<-data$MOTOZ1992_1992
data$motoz_1994<-data$MOTOZ1994_1994
data$motoz_1996<-data$MOTOZ1996_1996
data$motoz_1998<-data$MOTOZ1998_1998
data$motoz_2000<-data$MOTOZ2000_2000
data$motoz_2002<-data$MOTOZ2002_2002
data$motoz_2006<-data$MOTOZ2006_2006
data$motoz_2008<-data$MOTOZ2008_2008
data$motoz_2010<-data$MOTOZ2010_2010
data$motoz_2012<-data$MOTOZ2012_2012
data$motoz_2014<-data$MOTOZ2014_2014
data$motoz_2004<-NA

#################### DIGIT SPAN STD SCORES ############################

data$digitz_1986<-data$DIGITZ1986_1986
data$digitz_1988<-data$DIGITZ1988_1988
data$digitz_1990<-data$DIGITZ1990_1990
data$digitz_1992<-data$DIGITZ1992_1992
data$digitz_1994<-data$DIGITZ1994_1994
data$digitz_1996<-data$DIGITZ1996_1996
data$digitz_1998<-data$DIGITZ1998_1998
data$digitz_2000<-data$DIGITZ2000_2000
data$digitz_2002<-data$DIGITZ2002_2002
data$digitz_2004<-data$DIGITZ2004_2004
data$digitz_2006<-data$DIGITZ2006_2006
data$digitz_2008<-data$DIGITZ2008_2008
data$digitz_2010<-data$DIGITZ2010_2010
data$digitz_2012<-data$DIGITZ2012_2012
data$digitz_2014<-data$DIGITZ2014_2014


#################### PIAT MATH STD SCORES #############################

data$mathz_1986<-data$MATHZ1986_1986
data$mathz_1988<-data$MATHZ1988_1988
data$mathz_1990<-data$MATHZ1990_1990
data$mathz_1992<-data$MATHZ1992_1992
data$mathz_1994<-data$MATHZ1994_1994
data$mathz_1996<-data$MATHZ1996_1996
data$mathz_1998<-data$MATHZ1998_1998
data$mathz_2000<-data$MATHZ2000_2000
data$mathz_2002<-data$MATHZ2002_2002
data$mathz_2004<-data$MATHZ2004_2004
data$mathz_2006<-data$MATHZ2006_2006
data$mathz_2008<-data$MATHZ2008_2008
data$mathz_2010<-data$MATHZ2010_2010
data$mathz_2012<-data$MATHZ2012_2012
data$mathz_2014<-data$MATHZ2014_2014

#################### PIAT READING REGONITION STD SCORES #############################

data$recoz_1986<-data$RECOGZ1986_1986
data$recoz_1988<-data$RECOGZ1988_1988
data$recoz_1990<-data$RECOGZ1990_1990
data$recoz_1992<-data$RECOGZ1992_1992
data$recoz_1994<-data$RECOGZ1994_1994
data$recoz_1996<-data$RECOGZ1996_1996
data$recoz_1998<-data$RECOGZ1998_1998
data$recoz_2000<-data$RECOGZ2000_2000
data$recoz_2002<-data$RECOGZ2002_2002
data$recoz_2004<-data$RECOGZ2004_2004
data$recoz_2006<-data$RECOGZ2006_2006
data$recoz_2008<-data$RECOGZ2008_2008
data$recoz_2010<-data$RECOGZ2010_2010
data$recoz_2012<-data$RECOGZ2012_2012
data$recoz_2014<-data$RECOGZ2014_2014

#################### PIAT READING COMPREHENSION STD SCORES #############################

data$compz_1986<-data$COMPZ1986_1986
data$compz_1988<-data$COMPZ1988_1988
data$compz_1990<-data$COMPZ1990_1990
data$compz_1992<-data$COMPZ1992_1992
data$compz_1994<-data$COMPZ1994_1994
data$compz_1996<-data$COMPZ1996_1996
data$compz_1998<-data$COMPZ1998_1998
data$compz_2000<-data$COMPZ2000_2000
data$compz_2002<-data$COMPZ2002_2002
data$compz_2004<-data$COMPZ2004_2004
data$compz_2006<-data$COMPZ2006_2006
data$compz_2008<-data$COMPZ2008_2008
data$compz_2010<-data$COMPZ2010_2010
data$compz_2012<-data$COMPZ2012_2012
data$compz_2014<-data$COMPZ2014_2014

#################### PEABODY VOCABULARY STD SCORES #############################

data$vocaz_1986<-data$PPVTZ1986_1986
data$vocaz_1988<-data$PPVTZ1988_1988
data$vocaz_1990<-data$PPVTZ1990_1990
data$vocaz_1992<-data$PPVTZ1992_1992
data$vocaz_1994<-data$PPVTZ1994_1994
data$vocaz_1996<-data$PPVTZ1996_1996
data$vocaz_1998<-data$PPVTZ1998_1998
data$vocaz_2000<-data$PPVTZ2000_2000
data$vocaz_2002<-data$PPVTZ2002_2002
data$vocaz_2004<-data$PPVTZ2004_2004
data$vocaz_2006<-data$PPVTZ2006_2006
data$vocaz_2008<-data$PPVTZ2008_2008
data$vocaz_2010<-data$PPVTZ2010_2010
data$vocaz_2012<-data$PPVTZ2012_2012
data$vocaz_2014<-data$PPVTZ2014_2014

########################### CONTROLS #######################

### RESIDENCE ###

data$residence_1986<-data$CRES1986_1986
data$residence_1988<-data$CRES1988_1988
data$residence_1990<-data$CRES1990_1990
data$residence_1992<-data$CRES1992_1992
data$residence_1994<-data$CRES1994_1994
data$residence_1996<-data$CRES1996_1996
data$residence_1998<-data$CRES1998_1998
data$residence_2000<-data$CRES2000_2000
data$residence_2002<-data$CRES2002_2002
data$residence_2004<-data$CRES2004_2004
data$residence_2006<-data$CRES2006_2006
data$residence_2008<-data$CRES2008_2008
data$residence_2010<-data$CRES2010_2010
data$residence_2012<-data$CRES2012_2012
data$residence_2014<-data$CRES2014_2014



################### EXTRACTING VARIABLES ########################


myvars <- c("ID", "motherID","race", "sex",
            "datebirth", "birthorder", "birthage",
            "homez_1986", "homez_1988", "homez_1990",
            "homez_1992", "homez_1994", "homez_1996",
            "homez_1998", "homez_2000", "homez_2002",
            "homez_2004", "homez_2006", "homez_2008",
            "homez_2010", "homez_2012", "homez_2014",
            "cognz_1986", "cognz_1988", "cognz_1990",
            "cognz_1992", "cognz_1994", "cognz_1996",
            "cognz_1998", "cognz_2000", "cognz_2002",
            "cognz_2004", "cognz_2006", "cognz_2008",
            "cognz_2010", "cognz_2012", "cognz_2014",
            "emotz_1986", "emotz_1988", "emotz_1990",
            "emotz_1992", "emotz_1994", "emotz_1996",
            "emotz_1998", "emotz_2000", "emotz_2002",
            "emotz_2004", "emotz_2006", "emotz_2008",
            "emotz_2010", "emotz_2012", "emotz_2014",
            "mathz_1986", "mathz_1988", "mathz_1990",
            "mathz_1992", "mathz_1994", "mathz_1996",
            "mathz_1998", "mathz_2000", "mathz_2002",
            "mathz_2004", "mathz_2006", "mathz_2008",
            "mathz_2010", "mathz_2012", "mathz_2014",
            "compz_1986", "compz_1988", "compz_1990",
            "compz_1992", "compz_1994", "compz_1996",
            "compz_1998", "compz_2000", "compz_2002",
            "compz_2004", "compz_2006", "compz_2008",
            "compz_2010", "compz_2012", "compz_2014",
            "recoz_1986", "recoz_1988", "recoz_1990",
            "recoz_1992", "recoz_1994", "recoz_1996",
            "recoz_1998", "recoz_2000", "recoz_2002",
            "recoz_2004", "recoz_2006", "recoz_2008",
            "recoz_2010", "recoz_2012", "recoz_2014",
            "vocaz_1986", "vocaz_1988", "vocaz_1990",
            "vocaz_1992", "vocaz_1994", "vocaz_1996",
            "vocaz_1998", "vocaz_2000", "vocaz_2002",
            "vocaz_2004", "vocaz_2006", "vocaz_2008",
            "vocaz_2010", "vocaz_2012", "vocaz_2014",
            "motoz_1986", "motoz_1988", "motoz_1990",
            "motoz_1992", "motoz_1994", "motoz_1996",
            "motoz_1998", "motoz_2000", "motoz_2002",
            "motoz_2006", "motoz_2008", "motoz_2004",
            "motoz_2010", "motoz_2012", "motoz_2014",
            "digitz_1986", "digitz_1988", "digitz_1990",
            "digitz_1992", "digitz_1994", "digitz_1996",
            "digitz_1998", "digitz_2000", "digitz_2002",
            "digitz_2004", "digitz_2006", "digitz_2008",
            "digitz_2010", "digitz_2012", "digitz_2014",
            "residence_1986", "residence_1988", "residence_1990",
            "residence_1992", "residence_1994", "residence_1996",
            "residence_1998", "residence_2000", "residence_2002",
            "residence_2004", "residence_2006", "residence_2008",
            "residence_2010", "residence_2012", "residence_2014")
wide <- data[myvars]


##############################################################
######################### RESHAPING ##########################
##############################################################

long<-reshape(wide, idvar="ID", varying=8:157, timevar="YEAR", sep="_", direction="long")


#################################################################
########## MERGING WITH MOTHERS' EDUCATION ######################
################################################################

# Open both mother_educ data 

load("mother_educ.RData")

# Merge to create children's dataset

children<-merge(long, newdata, by="motherID",all.x=TRUE)


