
#################################################
####### IMPORT DATA ON OCCUPATIONS ############## 
#################################################

# ------------ This dataset can be obtained by uploading
# --------- the tagset occupations.NLSY79 
# ------- to the NLS Investigator platfom.
# -------- Note that this code is automatically generated by 
# --------- NLS investigator when you download the dataset.

new_data <- read.table('occupations.dat', sep=' ')
names(new_data) <- c('R0000100',
                     'R0046400',
                     'R0173600',
                     'R0214700',
                     'R0214800',
                     'R0263400',
                     'R0446400',
                     'R0702100',
                     'R0945000',
                     'R1255400',
                     'R1650200',
                     'R1922800',
                     'R2317600',
                     'R2525400',
                     'R2924400',
                     'R3127100',
                     'R3522800',
                     'R3727800',
                     'R4182100',
                     'R4587904',
                     'R5270600',
                     'R6472600',
                     'R6591800',
                     'R7209600',
                     'R7898000',
                     'T0138400',
                     'T1298000',
                     'T2326500',
                     'T3308700',
                     'T4282800',
                     'T5256900',
                     'T7818600')


# Handle missing values

new_data[new_data == -1] = NA  # Refused
new_data[new_data == -2] = NA  # Dont know
new_data[new_data == -3] = NA  # Invalid missing
new_data[new_data == -4] = NA  # Valid missing
new_data[new_data == -5] = NA  # Non-interview


# If there are values not categorized they will be represented as NA

vallabels = function(data) {
  data$R0173600 <- factor(data$R0173600,
                          levels=c(1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0),
                          labels=c("CROSS MALE WHITE",
                                   "CROSS MALE WH. POOR",
                                   "CROSS MALE BLACK",
                                   "CROSS MALE HISPANIC",
                                   "CROSS FEMALE WHITE",
                                   "CROSS FEMALE WH POOR",
                                   "CROSS FEMALE BLACK",
                                   "CROSS FEMALE HISPANIC",
                                   "SUP MALE WH POOR",
                                   "SUP MALE BLACK",
                                   "SUP MALE HISPANIC",
                                   "SUP FEM WH POOR",
                                   "SUP FEMALE BLACK",
                                   "SUP FEMALE HISPANIC",
                                   "MIL MALE WHITE",
                                   "MIL MALE BLACK",
                                   "MIL MALE HISPANIC",
                                   "MIL FEMALE WHITE",
                                   "MIL FEMALE BLACK",
                                   "MIL FEMALE HISPANIC"))
  data$R0214700 <- factor(data$R0214700,
                          levels=c(1.0,2.0,3.0),
                          labels=c("HISPANIC",
                                   "BLACK",
                                   "NON-BLACK, NON-HISPANIC"))
  data$R0214800 <- factor(data$R0214800,
                          levels=c(1.0,2.0),
                          labels=c("MALE",
                                   "FEMALE"))
  return(data)
}


# If there are values not categorized they will be represented as NA

vallabels_continuous = function(data) {
  data$R0046400[1.0 <= data$R0046400 & data$R0046400 <= 195.0] <- 1.0
  data$R0046400[201.0 <= data$R0046400 & data$R0046400 <= 245.0] <- 201.0
  data$R0046400[260.0 <= data$R0046400 & data$R0046400 <= 285.0] <- 260.0
  data$R0046400[301.0 <= data$R0046400 & data$R0046400 <= 395.0] <- 301.0
  data$R0046400[401.0 <= data$R0046400 & data$R0046400 <= 575.0] <- 401.0
  data$R0046400[580.0 <= data$R0046400 & data$R0046400 <= 590.0] <- 580.0
  data$R0046400[601.0 <= data$R0046400 & data$R0046400 <= 715.0] <- 601.0
  data$R0046400[740.0 <= data$R0046400 & data$R0046400 <= 785.0] <- 740.0
  data$R0046400[801.0 <= data$R0046400 & data$R0046400 <= 802.0] <- 801.0
  data$R0046400[821.0 <= data$R0046400 & data$R0046400 <= 824.0] <- 821.0
  data$R0046400[901.0 <= data$R0046400 & data$R0046400 <= 965.0] <- 901.0
  data$R0046400[980.0 <= data$R0046400 & data$R0046400 <= 984.0] <- 980.0
  data$R0046400 <- factor(data$R0046400,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R0263400[1.0 <= data$R0263400 & data$R0263400 <= 195.0] <- 1.0
  data$R0263400[201.0 <= data$R0263400 & data$R0263400 <= 245.0] <- 201.0
  data$R0263400[260.0 <= data$R0263400 & data$R0263400 <= 285.0] <- 260.0
  data$R0263400[301.0 <= data$R0263400 & data$R0263400 <= 395.0] <- 301.0
  data$R0263400[401.0 <= data$R0263400 & data$R0263400 <= 575.0] <- 401.0
  data$R0263400[580.0 <= data$R0263400 & data$R0263400 <= 590.0] <- 580.0
  data$R0263400[601.0 <= data$R0263400 & data$R0263400 <= 715.0] <- 601.0
  data$R0263400[740.0 <= data$R0263400 & data$R0263400 <= 785.0] <- 740.0
  data$R0263400[801.0 <= data$R0263400 & data$R0263400 <= 802.0] <- 801.0
  data$R0263400[821.0 <= data$R0263400 & data$R0263400 <= 824.0] <- 821.0
  data$R0263400[901.0 <= data$R0263400 & data$R0263400 <= 965.0] <- 901.0
  data$R0263400[980.0 <= data$R0263400 & data$R0263400 <= 984.0] <- 980.0
  data$R0263400 <- factor(data$R0263400,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R0446400[1.0 <= data$R0446400 & data$R0446400 <= 195.0] <- 1.0
  data$R0446400[201.0 <= data$R0446400 & data$R0446400 <= 245.0] <- 201.0
  data$R0446400[260.0 <= data$R0446400 & data$R0446400 <= 285.0] <- 260.0
  data$R0446400[301.0 <= data$R0446400 & data$R0446400 <= 395.0] <- 301.0
  data$R0446400[401.0 <= data$R0446400 & data$R0446400 <= 575.0] <- 401.0
  data$R0446400[580.0 <= data$R0446400 & data$R0446400 <= 590.0] <- 580.0
  data$R0446400[601.0 <= data$R0446400 & data$R0446400 <= 715.0] <- 601.0
  data$R0446400[740.0 <= data$R0446400 & data$R0446400 <= 785.0] <- 740.0
  data$R0446400[801.0 <= data$R0446400 & data$R0446400 <= 802.0] <- 801.0
  data$R0446400[821.0 <= data$R0446400 & data$R0446400 <= 824.0] <- 821.0
  data$R0446400[901.0 <= data$R0446400 & data$R0446400 <= 965.0] <- 901.0
  data$R0446400[980.0 <= data$R0446400 & data$R0446400 <= 984.0] <- 980.0
  data$R0446400 <- factor(data$R0446400,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R0702100[1.0 <= data$R0702100 & data$R0702100 <= 195.0] <- 1.0
  data$R0702100[201.0 <= data$R0702100 & data$R0702100 <= 245.0] <- 201.0
  data$R0702100[260.0 <= data$R0702100 & data$R0702100 <= 285.0] <- 260.0
  data$R0702100[301.0 <= data$R0702100 & data$R0702100 <= 395.0] <- 301.0
  data$R0702100[401.0 <= data$R0702100 & data$R0702100 <= 575.0] <- 401.0
  data$R0702100[580.0 <= data$R0702100 & data$R0702100 <= 590.0] <- 580.0
  data$R0702100[601.0 <= data$R0702100 & data$R0702100 <= 715.0] <- 601.0
  data$R0702100[740.0 <= data$R0702100 & data$R0702100 <= 785.0] <- 740.0
  data$R0702100[801.0 <= data$R0702100 & data$R0702100 <= 802.0] <- 801.0
  data$R0702100[821.0 <= data$R0702100 & data$R0702100 <= 824.0] <- 821.0
  data$R0702100[901.0 <= data$R0702100 & data$R0702100 <= 965.0] <- 901.0
  data$R0702100[980.0 <= data$R0702100 & data$R0702100 <= 984.0] <- 980.0
  data$R0702100 <- factor(data$R0702100,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R0945000[1.0 <= data$R0945000 & data$R0945000 <= 195.0] <- 1.0
  data$R0945000[201.0 <= data$R0945000 & data$R0945000 <= 245.0] <- 201.0
  data$R0945000[260.0 <= data$R0945000 & data$R0945000 <= 285.0] <- 260.0
  data$R0945000[301.0 <= data$R0945000 & data$R0945000 <= 395.0] <- 301.0
  data$R0945000[401.0 <= data$R0945000 & data$R0945000 <= 575.0] <- 401.0
  data$R0945000[580.0 <= data$R0945000 & data$R0945000 <= 590.0] <- 580.0
  data$R0945000[601.0 <= data$R0945000 & data$R0945000 <= 715.0] <- 601.0
  data$R0945000[740.0 <= data$R0945000 & data$R0945000 <= 785.0] <- 740.0
  data$R0945000[801.0 <= data$R0945000 & data$R0945000 <= 802.0] <- 801.0
  data$R0945000[821.0 <= data$R0945000 & data$R0945000 <= 824.0] <- 821.0
  data$R0945000[901.0 <= data$R0945000 & data$R0945000 <= 965.0] <- 901.0
  data$R0945000[980.0 <= data$R0945000 & data$R0945000 <= 984.0] <- 980.0
  data$R0945000 <- factor(data$R0945000,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R1255400[1.0 <= data$R1255400 & data$R1255400 <= 195.0] <- 1.0
  data$R1255400[201.0 <= data$R1255400 & data$R1255400 <= 245.0] <- 201.0
  data$R1255400[260.0 <= data$R1255400 & data$R1255400 <= 285.0] <- 260.0
  data$R1255400[301.0 <= data$R1255400 & data$R1255400 <= 395.0] <- 301.0
  data$R1255400[401.0 <= data$R1255400 & data$R1255400 <= 575.0] <- 401.0
  data$R1255400[580.0 <= data$R1255400 & data$R1255400 <= 590.0] <- 580.0
  data$R1255400[601.0 <= data$R1255400 & data$R1255400 <= 715.0] <- 601.0
  data$R1255400[740.0 <= data$R1255400 & data$R1255400 <= 785.0] <- 740.0
  data$R1255400[801.0 <= data$R1255400 & data$R1255400 <= 802.0] <- 801.0
  data$R1255400[821.0 <= data$R1255400 & data$R1255400 <= 824.0] <- 821.0
  data$R1255400[901.0 <= data$R1255400 & data$R1255400 <= 965.0] <- 901.0
  data$R1255400[980.0 <= data$R1255400 & data$R1255400 <= 984.0] <- 980.0
  data$R1255400 <- factor(data$R1255400,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R1650200[1.0 <= data$R1650200 & data$R1650200 <= 195.0] <- 1.0
  data$R1650200[201.0 <= data$R1650200 & data$R1650200 <= 245.0] <- 201.0
  data$R1650200[260.0 <= data$R1650200 & data$R1650200 <= 285.0] <- 260.0
  data$R1650200[301.0 <= data$R1650200 & data$R1650200 <= 395.0] <- 301.0
  data$R1650200[401.0 <= data$R1650200 & data$R1650200 <= 575.0] <- 401.0
  data$R1650200[580.0 <= data$R1650200 & data$R1650200 <= 590.0] <- 580.0
  data$R1650200[601.0 <= data$R1650200 & data$R1650200 <= 715.0] <- 601.0
  data$R1650200[740.0 <= data$R1650200 & data$R1650200 <= 785.0] <- 740.0
  data$R1650200[801.0 <= data$R1650200 & data$R1650200 <= 802.0] <- 801.0
  data$R1650200[821.0 <= data$R1650200 & data$R1650200 <= 824.0] <- 821.0
  data$R1650200[901.0 <= data$R1650200 & data$R1650200 <= 965.0] <- 901.0
  data$R1650200[980.0 <= data$R1650200 & data$R1650200 <= 984.0] <- 980.0
  data$R1650200 <- factor(data$R1650200,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R1922800[1.0 <= data$R1922800 & data$R1922800 <= 195.0] <- 1.0
  data$R1922800[201.0 <= data$R1922800 & data$R1922800 <= 245.0] <- 201.0
  data$R1922800[260.0 <= data$R1922800 & data$R1922800 <= 285.0] <- 260.0
  data$R1922800[301.0 <= data$R1922800 & data$R1922800 <= 395.0] <- 301.0
  data$R1922800[401.0 <= data$R1922800 & data$R1922800 <= 575.0] <- 401.0
  data$R1922800[580.0 <= data$R1922800 & data$R1922800 <= 590.0] <- 580.0
  data$R1922800[601.0 <= data$R1922800 & data$R1922800 <= 715.0] <- 601.0
  data$R1922800[740.0 <= data$R1922800 & data$R1922800 <= 785.0] <- 740.0
  data$R1922800[801.0 <= data$R1922800 & data$R1922800 <= 802.0] <- 801.0
  data$R1922800[821.0 <= data$R1922800 & data$R1922800 <= 824.0] <- 821.0
  data$R1922800[901.0 <= data$R1922800 & data$R1922800 <= 965.0] <- 901.0
  data$R1922800[980.0 <= data$R1922800 & data$R1922800 <= 984.0] <- 980.0
  data$R1922800 <- factor(data$R1922800,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R2317600[1.0 <= data$R2317600 & data$R2317600 <= 195.0] <- 1.0
  data$R2317600[201.0 <= data$R2317600 & data$R2317600 <= 245.0] <- 201.0
  data$R2317600[260.0 <= data$R2317600 & data$R2317600 <= 285.0] <- 260.0
  data$R2317600[301.0 <= data$R2317600 & data$R2317600 <= 395.0] <- 301.0
  data$R2317600[401.0 <= data$R2317600 & data$R2317600 <= 575.0] <- 401.0
  data$R2317600[580.0 <= data$R2317600 & data$R2317600 <= 590.0] <- 580.0
  data$R2317600[601.0 <= data$R2317600 & data$R2317600 <= 715.0] <- 601.0
  data$R2317600[740.0 <= data$R2317600 & data$R2317600 <= 785.0] <- 740.0
  data$R2317600[801.0 <= data$R2317600 & data$R2317600 <= 802.0] <- 801.0
  data$R2317600[821.0 <= data$R2317600 & data$R2317600 <= 824.0] <- 821.0
  data$R2317600[901.0 <= data$R2317600 & data$R2317600 <= 965.0] <- 901.0
  data$R2317600[980.0 <= data$R2317600 & data$R2317600 <= 984.0] <- 980.0
  data$R2317600 <- factor(data$R2317600,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R2525400[1.0 <= data$R2525400 & data$R2525400 <= 195.0] <- 1.0
  data$R2525400[201.0 <= data$R2525400 & data$R2525400 <= 245.0] <- 201.0
  data$R2525400[260.0 <= data$R2525400 & data$R2525400 <= 285.0] <- 260.0
  data$R2525400[301.0 <= data$R2525400 & data$R2525400 <= 395.0] <- 301.0
  data$R2525400[401.0 <= data$R2525400 & data$R2525400 <= 575.0] <- 401.0
  data$R2525400[580.0 <= data$R2525400 & data$R2525400 <= 590.0] <- 580.0
  data$R2525400[601.0 <= data$R2525400 & data$R2525400 <= 715.0] <- 601.0
  data$R2525400[740.0 <= data$R2525400 & data$R2525400 <= 785.0] <- 740.0
  data$R2525400[801.0 <= data$R2525400 & data$R2525400 <= 802.0] <- 801.0
  data$R2525400[821.0 <= data$R2525400 & data$R2525400 <= 824.0] <- 821.0
  data$R2525400[901.0 <= data$R2525400 & data$R2525400 <= 965.0] <- 901.0
  data$R2525400[980.0 <= data$R2525400 & data$R2525400 <= 984.0] <- 980.0
  data$R2525400 <- factor(data$R2525400,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R2924400[1.0 <= data$R2924400 & data$R2924400 <= 195.0] <- 1.0
  data$R2924400[201.0 <= data$R2924400 & data$R2924400 <= 245.0] <- 201.0
  data$R2924400[260.0 <= data$R2924400 & data$R2924400 <= 285.0] <- 260.0
  data$R2924400[301.0 <= data$R2924400 & data$R2924400 <= 395.0] <- 301.0
  data$R2924400[401.0 <= data$R2924400 & data$R2924400 <= 575.0] <- 401.0
  data$R2924400[580.0 <= data$R2924400 & data$R2924400 <= 590.0] <- 580.0
  data$R2924400[601.0 <= data$R2924400 & data$R2924400 <= 715.0] <- 601.0
  data$R2924400[740.0 <= data$R2924400 & data$R2924400 <= 785.0] <- 740.0
  data$R2924400[801.0 <= data$R2924400 & data$R2924400 <= 802.0] <- 801.0
  data$R2924400[821.0 <= data$R2924400 & data$R2924400 <= 824.0] <- 821.0
  data$R2924400[901.0 <= data$R2924400 & data$R2924400 <= 965.0] <- 901.0
  data$R2924400[980.0 <= data$R2924400 & data$R2924400 <= 984.0] <- 980.0
  data$R2924400 <- factor(data$R2924400,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R3127100[1.0 <= data$R3127100 & data$R3127100 <= 195.0] <- 1.0
  data$R3127100[201.0 <= data$R3127100 & data$R3127100 <= 245.0] <- 201.0
  data$R3127100[260.0 <= data$R3127100 & data$R3127100 <= 285.0] <- 260.0
  data$R3127100[301.0 <= data$R3127100 & data$R3127100 <= 395.0] <- 301.0
  data$R3127100[401.0 <= data$R3127100 & data$R3127100 <= 575.0] <- 401.0
  data$R3127100[580.0 <= data$R3127100 & data$R3127100 <= 590.0] <- 580.0
  data$R3127100[601.0 <= data$R3127100 & data$R3127100 <= 715.0] <- 601.0
  data$R3127100[740.0 <= data$R3127100 & data$R3127100 <= 785.0] <- 740.0
  data$R3127100[801.0 <= data$R3127100 & data$R3127100 <= 802.0] <- 801.0
  data$R3127100[821.0 <= data$R3127100 & data$R3127100 <= 824.0] <- 821.0
  data$R3127100[901.0 <= data$R3127100 & data$R3127100 <= 965.0] <- 901.0
  data$R3127100[980.0 <= data$R3127100 & data$R3127100 <= 984.0] <- 980.0
  data$R3127100 <- factor(data$R3127100,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R3522800[1.0 <= data$R3522800 & data$R3522800 <= 195.0] <- 1.0
  data$R3522800[201.0 <= data$R3522800 & data$R3522800 <= 245.0] <- 201.0
  data$R3522800[260.0 <= data$R3522800 & data$R3522800 <= 285.0] <- 260.0
  data$R3522800[301.0 <= data$R3522800 & data$R3522800 <= 395.0] <- 301.0
  data$R3522800[401.0 <= data$R3522800 & data$R3522800 <= 575.0] <- 401.0
  data$R3522800[580.0 <= data$R3522800 & data$R3522800 <= 590.0] <- 580.0
  data$R3522800[601.0 <= data$R3522800 & data$R3522800 <= 715.0] <- 601.0
  data$R3522800[740.0 <= data$R3522800 & data$R3522800 <= 785.0] <- 740.0
  data$R3522800[801.0 <= data$R3522800 & data$R3522800 <= 802.0] <- 801.0
  data$R3522800[821.0 <= data$R3522800 & data$R3522800 <= 824.0] <- 821.0
  data$R3522800[901.0 <= data$R3522800 & data$R3522800 <= 965.0] <- 901.0
  data$R3522800[980.0 <= data$R3522800 & data$R3522800 <= 984.0] <- 980.0
  data$R3522800 <- factor(data$R3522800,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R3727800[1.0 <= data$R3727800 & data$R3727800 <= 195.0] <- 1.0
  data$R3727800[201.0 <= data$R3727800 & data$R3727800 <= 245.0] <- 201.0
  data$R3727800[260.0 <= data$R3727800 & data$R3727800 <= 285.0] <- 260.0
  data$R3727800[301.0 <= data$R3727800 & data$R3727800 <= 395.0] <- 301.0
  data$R3727800[401.0 <= data$R3727800 & data$R3727800 <= 575.0] <- 401.0
  data$R3727800[580.0 <= data$R3727800 & data$R3727800 <= 590.0] <- 580.0
  data$R3727800[601.0 <= data$R3727800 & data$R3727800 <= 715.0] <- 601.0
  data$R3727800[740.0 <= data$R3727800 & data$R3727800 <= 785.0] <- 740.0
  data$R3727800[801.0 <= data$R3727800 & data$R3727800 <= 802.0] <- 801.0
  data$R3727800[821.0 <= data$R3727800 & data$R3727800 <= 824.0] <- 821.0
  data$R3727800[901.0 <= data$R3727800 & data$R3727800 <= 965.0] <- 901.0
  data$R3727800[980.0 <= data$R3727800 & data$R3727800 <= 984.0] <- 980.0
  data$R3727800 <- factor(data$R3727800,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R4182100[1.0 <= data$R4182100 & data$R4182100 <= 195.0] <- 1.0
  data$R4182100[201.0 <= data$R4182100 & data$R4182100 <= 245.0] <- 201.0
  data$R4182100[260.0 <= data$R4182100 & data$R4182100 <= 285.0] <- 260.0
  data$R4182100[301.0 <= data$R4182100 & data$R4182100 <= 395.0] <- 301.0
  data$R4182100[401.0 <= data$R4182100 & data$R4182100 <= 575.0] <- 401.0
  data$R4182100[580.0 <= data$R4182100 & data$R4182100 <= 590.0] <- 580.0
  data$R4182100[601.0 <= data$R4182100 & data$R4182100 <= 715.0] <- 601.0
  data$R4182100[740.0 <= data$R4182100 & data$R4182100 <= 785.0] <- 740.0
  data$R4182100[801.0 <= data$R4182100 & data$R4182100 <= 802.0] <- 801.0
  data$R4182100[821.0 <= data$R4182100 & data$R4182100 <= 824.0] <- 821.0
  data$R4182100[901.0 <= data$R4182100 & data$R4182100 <= 965.0] <- 901.0
  data$R4182100[980.0 <= data$R4182100 & data$R4182100 <= 984.0] <- 980.0
  data$R4182100 <- factor(data$R4182100,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0,996.0),
                          labels=c("0: 00      NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990: 990     SAME AS PRESENT JOB",
                                   "995: 995     DID NOT WORK",
                                   "996: 996     NEVER WORKED"))
  data$R4587904[1.0 <= data$R4587904 & data$R4587904 <= 195.0] <- 1.0
  data$R4587904[201.0 <= data$R4587904 & data$R4587904 <= 245.0] <- 201.0
  data$R4587904[260.0 <= data$R4587904 & data$R4587904 <= 285.0] <- 260.0
  data$R4587904[301.0 <= data$R4587904 & data$R4587904 <= 395.0] <- 301.0
  data$R4587904[401.0 <= data$R4587904 & data$R4587904 <= 575.0] <- 401.0
  data$R4587904[580.0 <= data$R4587904 & data$R4587904 <= 590.0] <- 580.0
  data$R4587904[601.0 <= data$R4587904 & data$R4587904 <= 715.0] <- 601.0
  data$R4587904[740.0 <= data$R4587904 & data$R4587904 <= 785.0] <- 740.0
  data$R4587904[801.0 <= data$R4587904 & data$R4587904 <= 802.0] <- 801.0
  data$R4587904[821.0 <= data$R4587904 & data$R4587904 <= 824.0] <- 821.0
  data$R4587904[901.0 <= data$R4587904 & data$R4587904 <= 965.0] <- 901.0
  data$R4587904[980.0 <= data$R4587904 & data$R4587904 <= 984.0] <- 980.0
  data$R4587904 <- factor(data$R4587904,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0),
                          labels=c("0: 000     NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990",
                                   "995: 995 OCCUPATION NOT REPORTED"))
  data$R5270600[1.0 <= data$R5270600 & data$R5270600 <= 195.0] <- 1.0
  data$R5270600[201.0 <= data$R5270600 & data$R5270600 <= 245.0] <- 201.0
  data$R5270600[260.0 <= data$R5270600 & data$R5270600 <= 285.0] <- 260.0
  data$R5270600[301.0 <= data$R5270600 & data$R5270600 <= 395.0] <- 301.0
  data$R5270600[401.0 <= data$R5270600 & data$R5270600 <= 575.0] <- 401.0
  data$R5270600[580.0 <= data$R5270600 & data$R5270600 <= 590.0] <- 580.0
  data$R5270600[601.0 <= data$R5270600 & data$R5270600 <= 715.0] <- 601.0
  data$R5270600[740.0 <= data$R5270600 & data$R5270600 <= 785.0] <- 740.0
  data$R5270600[801.0 <= data$R5270600 & data$R5270600 <= 802.0] <- 801.0
  data$R5270600[821.0 <= data$R5270600 & data$R5270600 <= 824.0] <- 821.0
  data$R5270600[901.0 <= data$R5270600 & data$R5270600 <= 965.0] <- 901.0
  data$R5270600[980.0 <= data$R5270600 & data$R5270600 <= 984.0] <- 980.0
  data$R5270600[995.0 <= data$R5270600 & data$R5270600 <= 996.0] <- 995.0
  data$R5270600 <- factor(data$R5270600,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0),
                          labels=c("0: NONE",
                                   "1 TO 195: PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: SALES WORKERS",
                                   "301 TO 395: CLERICAL AND KINDRED",
                                   "401 TO 575: CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: ARMED FORCES",
                                   "601 TO 715: OPERATIVES AND KINDRED",
                                   "740 TO 785: LABORERS, EXCEPT FARM",
                                   "801 TO 802: FARMERS AND FARM MANAGERS",
                                   "821 TO 824: FARM LABORERS AND FOREMAN",
                                   "901 TO 965: SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: PRIVATE HOUSEHOLD",
                                   "990: OCCUPATION NOT REPORTED",
                                   "995 TO 996: NEVER WORKED/DID NOT WORK DURING THAT PERIOD"))
  data$R6472600[1.0 <= data$R6472600 & data$R6472600 <= 195.0] <- 1.0
  data$R6472600[201.0 <= data$R6472600 & data$R6472600 <= 245.0] <- 201.0
  data$R6472600[260.0 <= data$R6472600 & data$R6472600 <= 285.0] <- 260.0
  data$R6472600[301.0 <= data$R6472600 & data$R6472600 <= 395.0] <- 301.0
  data$R6472600[401.0 <= data$R6472600 & data$R6472600 <= 575.0] <- 401.0
  data$R6472600[580.0 <= data$R6472600 & data$R6472600 <= 590.0] <- 580.0
  data$R6472600[601.0 <= data$R6472600 & data$R6472600 <= 715.0] <- 601.0
  data$R6472600[740.0 <= data$R6472600 & data$R6472600 <= 785.0] <- 740.0
  data$R6472600[801.0 <= data$R6472600 & data$R6472600 <= 802.0] <- 801.0
  data$R6472600[821.0 <= data$R6472600 & data$R6472600 <= 824.0] <- 821.0
  data$R6472600[901.0 <= data$R6472600 & data$R6472600 <= 965.0] <- 901.0
  data$R6472600[980.0 <= data$R6472600 & data$R6472600 <= 984.0] <- 980.0
  data$R6472600 <- factor(data$R6472600,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0),
                          labels=c("0: 000     NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990",
                                   "995: 995 OCCUPATION NOT REPORTED"))
  data$R6591800[1.0 <= data$R6591800 & data$R6591800 <= 195.0] <- 1.0
  data$R6591800[201.0 <= data$R6591800 & data$R6591800 <= 245.0] <- 201.0
  data$R6591800[260.0 <= data$R6591800 & data$R6591800 <= 285.0] <- 260.0
  data$R6591800[301.0 <= data$R6591800 & data$R6591800 <= 395.0] <- 301.0
  data$R6591800[401.0 <= data$R6591800 & data$R6591800 <= 575.0] <- 401.0
  data$R6591800[580.0 <= data$R6591800 & data$R6591800 <= 590.0] <- 580.0
  data$R6591800[601.0 <= data$R6591800 & data$R6591800 <= 715.0] <- 601.0
  data$R6591800[740.0 <= data$R6591800 & data$R6591800 <= 785.0] <- 740.0
  data$R6591800[801.0 <= data$R6591800 & data$R6591800 <= 802.0] <- 801.0
  data$R6591800[821.0 <= data$R6591800 & data$R6591800 <= 824.0] <- 821.0
  data$R6591800[901.0 <= data$R6591800 & data$R6591800 <= 965.0] <- 901.0
  data$R6591800[980.0 <= data$R6591800 & data$R6591800 <= 984.0] <- 980.0
  data$R6591800 <- factor(data$R6591800,
                          levels=c(0.0,1.0,201.0,260.0,301.0,401.0,580.0,601.0,740.0,801.0,821.0,901.0,980.0,990.0,995.0),
                          labels=c("0: 000     NONE",
                                   "1 TO 195: 001-195 PROFESSIONAL,TECHNICAL AND KINDRED",
                                   "201 TO 245: 201-245 MANAGERS,OFFICIALS AND PROPRIETORS",
                                   "260 TO 285: 260-285 SALES WORKERS",
                                   "301 TO 395: 301-395 CLERICAL AND KINDRED",
                                   "401 TO 575: 401-575 CRAFTSMEN,FOREMEN AND KINDRED",
                                   "580 TO 590: 580-590 ARMED FORCES",
                                   "601 TO 715: 601-715 OPERATIVES AND KINDRED",
                                   "740 TO 785: 740-785 LABORERS, EXCEPT FARM",
                                   "801 TO 802: 801-802 FARMERS AND FARM MANAGERS",
                                   "821 TO 824: 821-824 FARM LABORERS AND FOREMAN",
                                   "901 TO 965: 901-965 SERVICE WORKERS, EXCEPT PRIVATE HOUSEHOLD",
                                   "980 TO 984: 980-984 PRIVATE HOUSEHOLD",
                                   "990",
                                   "995: 995 OCCUPATION NOT REPORTED"))
  data$R7209600[1.0 <= data$R7209600 & data$R7209600 <= 43.0] <- 1.0
  data$R7209600[50.0 <= data$R7209600 & data$R7209600 <= 95.0] <- 50.0
  data$R7209600[100.0 <= data$R7209600 & data$R7209600 <= 124.0] <- 100.0
  data$R7209600[130.0 <= data$R7209600 & data$R7209600 <= 156.0] <- 130.0
  data$R7209600[160.0 <= data$R7209600 & data$R7209600 <= 196.0] <- 160.0
  data$R7209600[200.0 <= data$R7209600 & data$R7209600 <= 206.0] <- 200.0
  data$R7209600[210.0 <= data$R7209600 & data$R7209600 <= 215.0] <- 210.0
  data$R7209600[220.0 <= data$R7209600 & data$R7209600 <= 255.0] <- 220.0
  data$R7209600[260.0 <= data$R7209600 & data$R7209600 <= 296.0] <- 260.0
  data$R7209600[300.0 <= data$R7209600 & data$R7209600 <= 354.0] <- 300.0
  data$R7209600[360.0 <= data$R7209600 & data$R7209600 <= 365.0] <- 360.0
  data$R7209600[370.0 <= data$R7209600 & data$R7209600 <= 395.0] <- 370.0
  data$R7209600[400.0 <= data$R7209600 & data$R7209600 <= 416.0] <- 400.0
  data$R7209600[420.0 <= data$R7209600 & data$R7209600 <= 425.0] <- 420.0
  data$R7209600[430.0 <= data$R7209600 & data$R7209600 <= 465.0] <- 430.0
  data$R7209600[470.0 <= data$R7209600 & data$R7209600 <= 496.0] <- 470.0
  data$R7209600[500.0 <= data$R7209600 & data$R7209600 <= 593.0] <- 500.0
  data$R7209600[600.0 <= data$R7209600 & data$R7209600 <= 613.0] <- 600.0
  data$R7209600[620.0 <= data$R7209600 & data$R7209600 <= 694.0] <- 620.0
  data$R7209600[700.0 <= data$R7209600 & data$R7209600 <= 762.0] <- 700.0
  data$R7209600[770.0 <= data$R7209600 & data$R7209600 <= 896.0] <- 770.0
  data$R7209600[900.0 <= data$R7209600 & data$R7209600 <= 975.0] <- 900.0
  data$R7209600[980.0 <= data$R7209600 & data$R7209600 <= 983.0] <- 980.0
  data$R7209600 <- factor(data$R7209600,
                          levels=c(1.0,50.0,100.0,130.0,160.0,200.0,210.0,220.0,260.0,300.0,360.0,370.0,400.0,420.0,430.0,470.0,500.0,600.0,620.0,700.0,770.0,900.0,980.0),
                          labels=c("1 TO 43: Management",
                                   "50 TO 95: Business and Financial Operations",
                                   "100 TO 124: Computer and Mathematical",
                                   "130 TO 156: Architecture and Engineering",
                                   "160 TO 196: Life, Physical, and Social Services",
                                   "200 TO 206: Community and Social Services",
                                   "210 TO 215: Legal",
                                   "220 TO 255: Education, Training, and Library",
                                   "260 TO 296: Arts, Design, Entertainment, Sports, and Media",
                                   "300 TO 354: Healthcare Practitioners and Technical",
                                   "360 TO 365: Healthcare Support",
                                   "370 TO 395: Protective Service",
                                   "400 TO 416: Food Preparation and Serving Related",
                                   "420 TO 425: Building and Grounds Cleaning and Maintenance",
                                   "430 TO 465: Personal Care and Service",
                                   "470 TO 496: Sales and Related",
                                   "500 TO 593: Office and Administrative Support",
                                   "600 TO 613: Farming, Forestry, and Fishing",
                                   "620 TO 694: Construction and Extraction",
                                   "700 TO 762: Installation, Repair, and Maintenance",
                                   "770 TO 896: Production",
                                   "900 TO 975: Transportation and Material Moving",
                                   "980 TO 983: Military"))
  data$R7898000[10.0 <= data$R7898000 & data$R7898000 <= 430.0] <- 10.0
  data$R7898000[500.0 <= data$R7898000 & data$R7898000 <= 950.0] <- 500.0
  data$R7898000[1000.0 <= data$R7898000 & data$R7898000 <= 1240.0] <- 1000.0
  data$R7898000[1300.0 <= data$R7898000 & data$R7898000 <= 1560.0] <- 1300.0
  data$R7898000[1600.0 <= data$R7898000 & data$R7898000 <= 1760.0] <- 1600.0
  data$R7898000[1800.0 <= data$R7898000 & data$R7898000 <= 1860.0] <- 1800.0
  data$R7898000[1900.0 <= data$R7898000 & data$R7898000 <= 1960.0] <- 1900.0
  data$R7898000[2000.0 <= data$R7898000 & data$R7898000 <= 2060.0] <- 2000.0
  data$R7898000[2100.0 <= data$R7898000 & data$R7898000 <= 2150.0] <- 2100.0
  data$R7898000[2200.0 <= data$R7898000 & data$R7898000 <= 2340.0] <- 2200.0
  data$R7898000[2400.0 <= data$R7898000 & data$R7898000 <= 2550.0] <- 2400.0
  data$R7898000[2600.0 <= data$R7898000 & data$R7898000 <= 2760.0] <- 2600.0
  data$R7898000[2800.0 <= data$R7898000 & data$R7898000 <= 2960.0] <- 2800.0
  data$R7898000[3000.0 <= data$R7898000 & data$R7898000 <= 3260.0] <- 3000.0
  data$R7898000[3300.0 <= data$R7898000 & data$R7898000 <= 3650.0] <- 3300.0
  data$R7898000[3700.0 <= data$R7898000 & data$R7898000 <= 3950.0] <- 3700.0
  data$R7898000[4000.0 <= data$R7898000 & data$R7898000 <= 4160.0] <- 4000.0
  data$R7898000[4200.0 <= data$R7898000 & data$R7898000 <= 4250.0] <- 4200.0
  data$R7898000[4300.0 <= data$R7898000 & data$R7898000 <= 4430.0] <- 4300.0
  data$R7898000[4500.0 <= data$R7898000 & data$R7898000 <= 4650.0] <- 4500.0
  data$R7898000[4700.0 <= data$R7898000 & data$R7898000 <= 4960.0] <- 4700.0
  data$R7898000[5000.0 <= data$R7898000 & data$R7898000 <= 5930.0] <- 5000.0
  data$R7898000[6000.0 <= data$R7898000 & data$R7898000 <= 6130.0] <- 6000.0
  data$R7898000[6200.0 <= data$R7898000 & data$R7898000 <= 6940.0] <- 6200.0
  data$R7898000[7000.0 <= data$R7898000 & data$R7898000 <= 7620.0] <- 7000.0
  data$R7898000[7700.0 <= data$R7898000 & data$R7898000 <= 7750.0] <- 7700.0
  data$R7898000[7800.0 <= data$R7898000 & data$R7898000 <= 7850.0] <- 7800.0
  data$R7898000[7900.0 <= data$R7898000 & data$R7898000 <= 8960.0] <- 7900.0
  data$R7898000[9000.0 <= data$R7898000 & data$R7898000 <= 9750.0] <- 9000.0
  data$R7898000[9800.0 <= data$R7898000 & data$R7898000 <= 9830.0] <- 9800.0
  data$R7898000 <- factor(data$R7898000,
                          levels=c(10.0,500.0,1000.0,1300.0,1600.0,1800.0,1900.0,2000.0,2100.0,2200.0,2400.0,2600.0,2800.0,3000.0,3300.0,3700.0,4000.0,4200.0,4300.0,4460.0,4500.0,4700.0,5000.0,6000.0,6200.0,7000.0,7700.0,7800.0,7900.0,9000.0,9800.0,9840.0,9950.0,9990.0),
                          labels=c("10 TO 430: Executive, Administrative and Managerial Occupations",
                                   "500 TO 950: Management Related Occupations",
                                   "1000 TO 1240: Mathematical and Computer Scientists",
                                   "1300 TO 1560: Engineers, Architects, Surveyers, Engineering and Related Technicians",
                                   "1600 TO 1760: Physical Scientists",
                                   "1800 TO 1860: Social Scientists and Related Workers",
                                   "1900 TO 1960: Life, Physical and Social Science Technicians",
                                   "2000 TO 2060: Counselors, Sociala and Religious Workers",
                                   "2100 TO 2150: Lawyers, Judges and Legal Support Workers",
                                   "2200 TO 2340: Teachers",
                                   "2400 TO 2550: Education, Training and Library Workers",
                                   "2600 TO 2760: Entertainers and Performers, Sports and Related Workers",
                                   "2800 TO 2960: Media and Communications Workers",
                                   "3000 TO 3260: Health Diagnosing and Treating Practitioners",
                                   "3300 TO 3650: Health Care Technical and Support Occupations",
                                   "3700 TO 3950: Protective Service Occupations",
                                   "4000 TO 4160: Food Preparation and Serving Related Occupations",
                                   "4200 TO 4250: Cleaning and Building Service Occupations",
                                   "4300 TO 4430: Entertainment Attendants and Related Workers",
                                   "4460: Funeral Related Occupations",
                                   "4500 TO 4650: Personal Care and Service Workers",
                                   "4700 TO 4960: Sales and Related Workers",
                                   "5000 TO 5930: Office and Administrative Support Workers",
                                   "6000 TO 6130: Farming, Fishing and Forestry Occupations",
                                   "6200 TO 6940: Construction Trade and Extraction Workers",
                                   "7000 TO 7620: Installation, Maintenance and Repairs Workers",
                                   "7700 TO 7750: Production and Operating Workers",
                                   "7800 TO 7850: Food Preparation Occupations",
                                   "7900 TO 8960: Setters, Operators and Tenders",
                                   "9000 TO 9750: Transportation and Material Moving Workers",
                                   "9800 TO 9830: Military Specific Occupations",
                                   "9840: Armed Forces",
                                   "9950: Not in Labor Force (ACS Code)",
                                   "9990: Uncodeable"))
  data$T0138400[10.0 <= data$T0138400 & data$T0138400 <= 430.0] <- 10.0
  data$T0138400[500.0 <= data$T0138400 & data$T0138400 <= 950.0] <- 500.0
  data$T0138400[1000.0 <= data$T0138400 & data$T0138400 <= 1240.0] <- 1000.0
  data$T0138400[1300.0 <= data$T0138400 & data$T0138400 <= 1560.0] <- 1300.0
  data$T0138400[1600.0 <= data$T0138400 & data$T0138400 <= 1760.0] <- 1600.0
  data$T0138400[1800.0 <= data$T0138400 & data$T0138400 <= 1860.0] <- 1800.0
  data$T0138400[1900.0 <= data$T0138400 & data$T0138400 <= 1960.0] <- 1900.0
  data$T0138400[2000.0 <= data$T0138400 & data$T0138400 <= 2060.0] <- 2000.0
  data$T0138400[2100.0 <= data$T0138400 & data$T0138400 <= 2150.0] <- 2100.0
  data$T0138400[2200.0 <= data$T0138400 & data$T0138400 <= 2340.0] <- 2200.0
  data$T0138400[2400.0 <= data$T0138400 & data$T0138400 <= 2550.0] <- 2400.0
  data$T0138400[2600.0 <= data$T0138400 & data$T0138400 <= 2760.0] <- 2600.0
  data$T0138400[2800.0 <= data$T0138400 & data$T0138400 <= 2960.0] <- 2800.0
  data$T0138400[3000.0 <= data$T0138400 & data$T0138400 <= 3260.0] <- 3000.0
  data$T0138400[3300.0 <= data$T0138400 & data$T0138400 <= 3650.0] <- 3300.0
  data$T0138400[3700.0 <= data$T0138400 & data$T0138400 <= 3950.0] <- 3700.0
  data$T0138400[4000.0 <= data$T0138400 & data$T0138400 <= 4160.0] <- 4000.0
  data$T0138400[4200.0 <= data$T0138400 & data$T0138400 <= 4250.0] <- 4200.0
  data$T0138400[4300.0 <= data$T0138400 & data$T0138400 <= 4430.0] <- 4300.0
  data$T0138400[4500.0 <= data$T0138400 & data$T0138400 <= 4650.0] <- 4500.0
  data$T0138400[4700.0 <= data$T0138400 & data$T0138400 <= 4960.0] <- 4700.0
  data$T0138400[5000.0 <= data$T0138400 & data$T0138400 <= 5930.0] <- 5000.0
  data$T0138400[6000.0 <= data$T0138400 & data$T0138400 <= 6130.0] <- 6000.0
  data$T0138400[6200.0 <= data$T0138400 & data$T0138400 <= 6940.0] <- 6200.0
  data$T0138400[7000.0 <= data$T0138400 & data$T0138400 <= 7620.0] <- 7000.0
  data$T0138400[7700.0 <= data$T0138400 & data$T0138400 <= 7750.0] <- 7700.0
  data$T0138400[7800.0 <= data$T0138400 & data$T0138400 <= 7850.0] <- 7800.0
  data$T0138400[7900.0 <= data$T0138400 & data$T0138400 <= 8960.0] <- 7900.0
  data$T0138400[9000.0 <= data$T0138400 & data$T0138400 <= 9750.0] <- 9000.0
  data$T0138400[9800.0 <= data$T0138400 & data$T0138400 <= 9830.0] <- 9800.0
  data$T0138400 <- factor(data$T0138400,
                          levels=c(10.0,500.0,1000.0,1300.0,1600.0,1800.0,1900.0,2000.0,2100.0,2200.0,2400.0,2600.0,2800.0,3000.0,3300.0,3700.0,4000.0,4200.0,4300.0,4460.0,4500.0,4700.0,5000.0,6000.0,6200.0,7000.0,7700.0,7800.0,7900.0,9000.0,9800.0,9840.0,9950.0,9990.0),
                          labels=c("10 TO 430: Executive, Administrative and Managerial Occupations",
                                   "500 TO 950: Management Related Occupations",
                                   "1000 TO 1240: Mathematical and Computer Scientists",
                                   "1300 TO 1560: Engineers, Architects, Surveyers, Engineering and Related Technicians",
                                   "1600 TO 1760: Physical Scientists",
                                   "1800 TO 1860: Social Scientists and Related Workers",
                                   "1900 TO 1960: Life, Physical and Social Science Technicians",
                                   "2000 TO 2060: Counselors, Sociala and Religious Workers",
                                   "2100 TO 2150: Lawyers, Judges and Legal Support Workers",
                                   "2200 TO 2340: Teachers",
                                   "2400 TO 2550: Education, Training and Library Workers",
                                   "2600 TO 2760: Entertainers and Performers, Sports and Related Workers",
                                   "2800 TO 2960: Media and Communications Workers",
                                   "3000 TO 3260: Health Diagnosing and Treating Practitioners",
                                   "3300 TO 3650: Health Care Technical and Support Occupations",
                                   "3700 TO 3950: Protective Service Occupations",
                                   "4000 TO 4160: Food Preparation and Serving Related Occupations",
                                   "4200 TO 4250: Cleaning and Building Service Occupations",
                                   "4300 TO 4430: Entertainment Attendants and Related Workers",
                                   "4460: Funeral Related Occupations",
                                   "4500 TO 4650: Personal Care and Service Workers",
                                   "4700 TO 4960: Sales and Related Workers",
                                   "5000 TO 5930: Office and Administrative Support Workers",
                                   "6000 TO 6130: Farming, Fishing and Forestry Occupations",
                                   "6200 TO 6940: Construction Trade and Extraction Workers",
                                   "7000 TO 7620: Installation, Maintenance and Repairs Workers",
                                   "7700 TO 7750: Production and Operating Workers",
                                   "7800 TO 7850: Food Preparation Occupations",
                                   "7900 TO 8960: Setters, Operators and Tenders",
                                   "9000 TO 9750: Transportation and Material Moving Workers",
                                   "9800 TO 9830: Military Specific Occupations",
                                   "9840: Armed Forces",
                                   "9950: Not in Labor Force (ACS Code)",
                                   "9990: Uncodeable"))
  data$T1298000[10.0 <= data$T1298000 & data$T1298000 <= 430.0] <- 10.0
  data$T1298000[500.0 <= data$T1298000 & data$T1298000 <= 950.0] <- 500.0
  data$T1298000[1000.0 <= data$T1298000 & data$T1298000 <= 1240.0] <- 1000.0
  data$T1298000[1300.0 <= data$T1298000 & data$T1298000 <= 1560.0] <- 1300.0
  data$T1298000[1600.0 <= data$T1298000 & data$T1298000 <= 1760.0] <- 1600.0
  data$T1298000[1800.0 <= data$T1298000 & data$T1298000 <= 1860.0] <- 1800.0
  data$T1298000[1900.0 <= data$T1298000 & data$T1298000 <= 1960.0] <- 1900.0
  data$T1298000[2000.0 <= data$T1298000 & data$T1298000 <= 2060.0] <- 2000.0
  data$T1298000[2100.0 <= data$T1298000 & data$T1298000 <= 2150.0] <- 2100.0
  data$T1298000[2200.0 <= data$T1298000 & data$T1298000 <= 2340.0] <- 2200.0
  data$T1298000[2400.0 <= data$T1298000 & data$T1298000 <= 2550.0] <- 2400.0
  data$T1298000[2600.0 <= data$T1298000 & data$T1298000 <= 2760.0] <- 2600.0
  data$T1298000[2800.0 <= data$T1298000 & data$T1298000 <= 2960.0] <- 2800.0
  data$T1298000[3000.0 <= data$T1298000 & data$T1298000 <= 3260.0] <- 3000.0
  data$T1298000[3300.0 <= data$T1298000 & data$T1298000 <= 3650.0] <- 3300.0
  data$T1298000[3700.0 <= data$T1298000 & data$T1298000 <= 3950.0] <- 3700.0
  data$T1298000[4000.0 <= data$T1298000 & data$T1298000 <= 4160.0] <- 4000.0
  data$T1298000[4200.0 <= data$T1298000 & data$T1298000 <= 4250.0] <- 4200.0
  data$T1298000[4300.0 <= data$T1298000 & data$T1298000 <= 4430.0] <- 4300.0
  data$T1298000[4500.0 <= data$T1298000 & data$T1298000 <= 4650.0] <- 4500.0
  data$T1298000[4700.0 <= data$T1298000 & data$T1298000 <= 4960.0] <- 4700.0
  data$T1298000[5000.0 <= data$T1298000 & data$T1298000 <= 5930.0] <- 5000.0
  data$T1298000[6000.0 <= data$T1298000 & data$T1298000 <= 6130.0] <- 6000.0
  data$T1298000[6200.0 <= data$T1298000 & data$T1298000 <= 6940.0] <- 6200.0
  data$T1298000[7000.0 <= data$T1298000 & data$T1298000 <= 7620.0] <- 7000.0
  data$T1298000[7700.0 <= data$T1298000 & data$T1298000 <= 7750.0] <- 7700.0
  data$T1298000[7800.0 <= data$T1298000 & data$T1298000 <= 7850.0] <- 7800.0
  data$T1298000[7900.0 <= data$T1298000 & data$T1298000 <= 8960.0] <- 7900.0
  data$T1298000[9000.0 <= data$T1298000 & data$T1298000 <= 9750.0] <- 9000.0
  data$T1298000[9800.0 <= data$T1298000 & data$T1298000 <= 9830.0] <- 9800.0
  data$T1298000 <- factor(data$T1298000,
                          levels=c(10.0,500.0,1000.0,1300.0,1600.0,1800.0,1900.0,2000.0,2100.0,2200.0,2400.0,2600.0,2800.0,3000.0,3300.0,3700.0,4000.0,4200.0,4300.0,4460.0,4500.0,4700.0,5000.0,6000.0,6200.0,7000.0,7700.0,7800.0,7900.0,9000.0,9800.0,9840.0,9950.0,9990.0),
                          labels=c("10 TO 430: Executive, Administrative and Managerial Occupations",
                                   "500 TO 950: Management Related Occupations",
                                   "1000 TO 1240: Mathematical and Computer Scientists",
                                   "1300 TO 1560: Engineers, Architects, Surveyers, Engineering and Related Technicians",
                                   "1600 TO 1760: Physical Scientists",
                                   "1800 TO 1860: Social Scientists and Related Workers",
                                   "1900 TO 1960: Life, Physical and Social Science Technicians",
                                   "2000 TO 2060: Counselors, Sociala and Religious Workers",
                                   "2100 TO 2150: Lawyers, Judges and Legal Support Workers",
                                   "2200 TO 2340: Teachers",
                                   "2400 TO 2550: Education, Training and Library Workers",
                                   "2600 TO 2760: Entertainers and Performers, Sports and Related Workers",
                                   "2800 TO 2960: Media and Communications Workers",
                                   "3000 TO 3260: Health Diagnosing and Treating Practitioners",
                                   "3300 TO 3650: Health Care Technical and Support Occupations",
                                   "3700 TO 3950: Protective Service Occupations",
                                   "4000 TO 4160: Food Preparation and Serving Related Occupations",
                                   "4200 TO 4250: Cleaning and Building Service Occupations",
                                   "4300 TO 4430: Entertainment Attendants and Related Workers",
                                   "4460: Funeral Related Occupations",
                                   "4500 TO 4650: Personal Care and Service Workers",
                                   "4700 TO 4960: Sales and Related Workers",
                                   "5000 TO 5930: Office and Administrative Support Workers",
                                   "6000 TO 6130: Farming, Fishing and Forestry Occupations",
                                   "6200 TO 6940: Construction Trade and Extraction Workers",
                                   "7000 TO 7620: Installation, Maintenance and Repairs Workers",
                                   "7700 TO 7750: Production and Operating Workers",
                                   "7800 TO 7850: Food Preparation Occupations",
                                   "7900 TO 8960: Setters, Operators and Tenders",
                                   "9000 TO 9750: Transportation and Material Moving Workers",
                                   "9800 TO 9830: Military Specific Occupations",
                                   "9840: Armed Forces",
                                   "9950: Not in Labor Force (ACS Code)",
                                   "9990: Uncodeable"))
  data$T2326500[10.0 <= data$T2326500 & data$T2326500 <= 430.0] <- 10.0
  data$T2326500[500.0 <= data$T2326500 & data$T2326500 <= 950.0] <- 500.0
  data$T2326500[1000.0 <= data$T2326500 & data$T2326500 <= 1240.0] <- 1000.0
  data$T2326500[1300.0 <= data$T2326500 & data$T2326500 <= 1560.0] <- 1300.0
  data$T2326500[1600.0 <= data$T2326500 & data$T2326500 <= 1760.0] <- 1600.0
  data$T2326500[1800.0 <= data$T2326500 & data$T2326500 <= 1860.0] <- 1800.0
  data$T2326500[1900.0 <= data$T2326500 & data$T2326500 <= 1960.0] <- 1900.0
  data$T2326500[2000.0 <= data$T2326500 & data$T2326500 <= 2060.0] <- 2000.0
  data$T2326500[2100.0 <= data$T2326500 & data$T2326500 <= 2150.0] <- 2100.0
  data$T2326500[2200.0 <= data$T2326500 & data$T2326500 <= 2340.0] <- 2200.0
  data$T2326500[2400.0 <= data$T2326500 & data$T2326500 <= 2550.0] <- 2400.0
  data$T2326500[2600.0 <= data$T2326500 & data$T2326500 <= 2760.0] <- 2600.0
  data$T2326500[2800.0 <= data$T2326500 & data$T2326500 <= 2960.0] <- 2800.0
  data$T2326500[3000.0 <= data$T2326500 & data$T2326500 <= 3260.0] <- 3000.0
  data$T2326500[3300.0 <= data$T2326500 & data$T2326500 <= 3650.0] <- 3300.0
  data$T2326500[3700.0 <= data$T2326500 & data$T2326500 <= 3950.0] <- 3700.0
  data$T2326500[4000.0 <= data$T2326500 & data$T2326500 <= 4160.0] <- 4000.0
  data$T2326500[4200.0 <= data$T2326500 & data$T2326500 <= 4250.0] <- 4200.0
  data$T2326500[4300.0 <= data$T2326500 & data$T2326500 <= 4430.0] <- 4300.0
  data$T2326500[4500.0 <= data$T2326500 & data$T2326500 <= 4650.0] <- 4500.0
  data$T2326500[4700.0 <= data$T2326500 & data$T2326500 <= 4960.0] <- 4700.0
  data$T2326500[5000.0 <= data$T2326500 & data$T2326500 <= 5930.0] <- 5000.0
  data$T2326500[6000.0 <= data$T2326500 & data$T2326500 <= 6130.0] <- 6000.0
  data$T2326500[6200.0 <= data$T2326500 & data$T2326500 <= 6940.0] <- 6200.0
  data$T2326500[7000.0 <= data$T2326500 & data$T2326500 <= 7620.0] <- 7000.0
  data$T2326500[7700.0 <= data$T2326500 & data$T2326500 <= 7750.0] <- 7700.0
  data$T2326500[7800.0 <= data$T2326500 & data$T2326500 <= 7850.0] <- 7800.0
  data$T2326500[7900.0 <= data$T2326500 & data$T2326500 <= 8960.0] <- 7900.0
  data$T2326500[9000.0 <= data$T2326500 & data$T2326500 <= 9750.0] <- 9000.0
  data$T2326500[9800.0 <= data$T2326500 & data$T2326500 <= 9830.0] <- 9800.0
  data$T2326500 <- factor(data$T2326500,
                          levels=c(10.0,500.0,1000.0,1300.0,1600.0,1800.0,1900.0,2000.0,2100.0,2200.0,2400.0,2600.0,2800.0,3000.0,3300.0,3700.0,4000.0,4200.0,4300.0,4460.0,4500.0,4700.0,5000.0,6000.0,6200.0,7000.0,7700.0,7800.0,7900.0,9000.0,9800.0,9840.0,9950.0,9990.0),
                          labels=c("10 TO 430: Executive, Administrative and Managerial Occupations",
                                   "500 TO 950: Management Related Occupations",
                                   "1000 TO 1240: Mathematical and Computer Scientists",
                                   "1300 TO 1560: Engineers, Architects, Surveyers, Engineering and Related Technicians",
                                   "1600 TO 1760: Physical Scientists",
                                   "1800 TO 1860: Social Scientists and Related Workers",
                                   "1900 TO 1960: Life, Physical and Social Science Technicians",
                                   "2000 TO 2060: Counselors, Sociala and Religious Workers",
                                   "2100 TO 2150: Lawyers, Judges and Legal Support Workers",
                                   "2200 TO 2340: Teachers",
                                   "2400 TO 2550: Education, Training and Library Workers",
                                   "2600 TO 2760: Entertainers and Performers, Sports and Related Workers",
                                   "2800 TO 2960: Media and Communications Workers",
                                   "3000 TO 3260: Health Diagnosing and Treating Practitioners",
                                   "3300 TO 3650: Health Care Technical and Support Occupations",
                                   "3700 TO 3950: Protective Service Occupations",
                                   "4000 TO 4160: Food Preparation and Serving Related Occupations",
                                   "4200 TO 4250: Cleaning and Building Service Occupations",
                                   "4300 TO 4430: Entertainment Attendants and Related Workers",
                                   "4460: Funeral Related Occupations",
                                   "4500 TO 4650: Personal Care and Service Workers",
                                   "4700 TO 4960: Sales and Related Workers",
                                   "5000 TO 5930: Office and Administrative Support Workers",
                                   "6000 TO 6130: Farming, Fishing and Forestry Occupations",
                                   "6200 TO 6940: Construction Trade and Extraction Workers",
                                   "7000 TO 7620: Installation, Maintenance and Repairs Workers",
                                   "7700 TO 7750: Production and Operating Workers",
                                   "7800 TO 7850: Food Preparation Occupations",
                                   "7900 TO 8960: Setters, Operators and Tenders",
                                   "9000 TO 9750: Transportation and Material Moving Workers",
                                   "9800 TO 9830: Military Specific Occupations",
                                   "9840: Armed Forces",
                                   "9950: Not in Labor Force (ACS Code)",
                                   "9990: Uncodeable"))
  data$T3308700[10.0 <= data$T3308700 & data$T3308700 <= 430.0] <- 10.0
  data$T3308700[500.0 <= data$T3308700 & data$T3308700 <= 950.0] <- 500.0
  data$T3308700[1000.0 <= data$T3308700 & data$T3308700 <= 1240.0] <- 1000.0
  data$T3308700[1300.0 <= data$T3308700 & data$T3308700 <= 1560.0] <- 1300.0
  data$T3308700[1600.0 <= data$T3308700 & data$T3308700 <= 1760.0] <- 1600.0
  data$T3308700[1800.0 <= data$T3308700 & data$T3308700 <= 1860.0] <- 1800.0
  data$T3308700[1900.0 <= data$T3308700 & data$T3308700 <= 1960.0] <- 1900.0
  data$T3308700[2000.0 <= data$T3308700 & data$T3308700 <= 2060.0] <- 2000.0
  data$T3308700[2100.0 <= data$T3308700 & data$T3308700 <= 2150.0] <- 2100.0
  data$T3308700[2200.0 <= data$T3308700 & data$T3308700 <= 2340.0] <- 2200.0
  data$T3308700[2400.0 <= data$T3308700 & data$T3308700 <= 2550.0] <- 2400.0
  data$T3308700[2600.0 <= data$T3308700 & data$T3308700 <= 2760.0] <- 2600.0
  data$T3308700[2800.0 <= data$T3308700 & data$T3308700 <= 2960.0] <- 2800.0
  data$T3308700[3000.0 <= data$T3308700 & data$T3308700 <= 3260.0] <- 3000.0
  data$T3308700[3300.0 <= data$T3308700 & data$T3308700 <= 3650.0] <- 3300.0
  data$T3308700[3700.0 <= data$T3308700 & data$T3308700 <= 3950.0] <- 3700.0
  data$T3308700[4000.0 <= data$T3308700 & data$T3308700 <= 4160.0] <- 4000.0
  data$T3308700[4200.0 <= data$T3308700 & data$T3308700 <= 4250.0] <- 4200.0
  data$T3308700[4300.0 <= data$T3308700 & data$T3308700 <= 4430.0] <- 4300.0
  data$T3308700[4500.0 <= data$T3308700 & data$T3308700 <= 4650.0] <- 4500.0
  data$T3308700[4700.0 <= data$T3308700 & data$T3308700 <= 4960.0] <- 4700.0
  data$T3308700[5000.0 <= data$T3308700 & data$T3308700 <= 5930.0] <- 5000.0
  data$T3308700[6000.0 <= data$T3308700 & data$T3308700 <= 6130.0] <- 6000.0
  data$T3308700[6200.0 <= data$T3308700 & data$T3308700 <= 6940.0] <- 6200.0
  data$T3308700[7000.0 <= data$T3308700 & data$T3308700 <= 7620.0] <- 7000.0
  data$T3308700[7700.0 <= data$T3308700 & data$T3308700 <= 7750.0] <- 7700.0
  data$T3308700[7800.0 <= data$T3308700 & data$T3308700 <= 7850.0] <- 7800.0
  data$T3308700[7900.0 <= data$T3308700 & data$T3308700 <= 8960.0] <- 7900.0
  data$T3308700[9000.0 <= data$T3308700 & data$T3308700 <= 9750.0] <- 9000.0
  data$T3308700[9800.0 <= data$T3308700 & data$T3308700 <= 9830.0] <- 9800.0
  data$T3308700 <- factor(data$T3308700,
                          levels=c(10.0,500.0,1000.0,1300.0,1600.0,1800.0,1900.0,2000.0,2100.0,2200.0,2400.0,2600.0,2800.0,3000.0,3300.0,3700.0,4000.0,4200.0,4300.0,4460.0,4500.0,4700.0,5000.0,6000.0,6200.0,7000.0,7700.0,7800.0,7900.0,9000.0,9800.0,9840.0,9950.0,9990.0),
                          labels=c("10 TO 430: Executive, Administrative and Managerial Occupations",
                                   "500 TO 950: Management Related Occupations",
                                   "1000 TO 1240: Mathematical and Computer Scientists",
                                   "1300 TO 1560: Engineers, Architects, Surveyers, Engineering and Related Technicians",
                                   "1600 TO 1760: Physical Scientists",
                                   "1800 TO 1860: Social Scientists and Related Workers",
                                   "1900 TO 1960: Life, Physical and Social Science Technicians",
                                   "2000 TO 2060: Counselors, Sociala and Religious Workers",
                                   "2100 TO 2150: Lawyers, Judges and Legal Support Workers",
                                   "2200 TO 2340: Teachers",
                                   "2400 TO 2550: Education, Training and Library Workers",
                                   "2600 TO 2760: Entertainers and Performers, Sports and Related Workers",
                                   "2800 TO 2960: Media and Communications Workers",
                                   "3000 TO 3260: Health Diagnosing and Treating Practitioners",
                                   "3300 TO 3650: Health Care Technical and Support Occupations",
                                   "3700 TO 3950: Protective Service Occupations",
                                   "4000 TO 4160: Food Preparation and Serving Related Occupations",
                                   "4200 TO 4250: Cleaning and Building Service Occupations",
                                   "4300 TO 4430: Entertainment Attendants and Related Workers",
                                   "4460: Funeral Related Occupations",
                                   "4500 TO 4650: Personal Care and Service Workers",
                                   "4700 TO 4960: Sales and Related Workers",
                                   "5000 TO 5930: Office and Administrative Support Workers",
                                   "6000 TO 6130: Farming, Fishing and Forestry Occupations",
                                   "6200 TO 6940: Construction Trade and Extraction Workers",
                                   "7000 TO 7620: Installation, Maintenance and Repairs Workers",
                                   "7700 TO 7750: Production and Operating Workers",
                                   "7800 TO 7850: Food Preparation Occupations",
                                   "7900 TO 8960: Setters, Operators and Tenders",
                                   "9000 TO 9750: Transportation and Material Moving Workers",
                                   "9800 TO 9830: Military Specific Occupations",
                                   "9840: Armed Forces",
                                   "9950: Not in Labor Force (ACS Code)",
                                   "9990: Uncodeable"))
  data$T4282800[10.0 <= data$T4282800 & data$T4282800 <= 430.0] <- 10.0
  data$T4282800[500.0 <= data$T4282800 & data$T4282800 <= 950.0] <- 500.0
  data$T4282800[1000.0 <= data$T4282800 & data$T4282800 <= 1240.0] <- 1000.0
  data$T4282800[1300.0 <= data$T4282800 & data$T4282800 <= 1560.0] <- 1300.0
  data$T4282800[1600.0 <= data$T4282800 & data$T4282800 <= 1760.0] <- 1600.0
  data$T4282800[1800.0 <= data$T4282800 & data$T4282800 <= 1860.0] <- 1800.0
  data$T4282800[1900.0 <= data$T4282800 & data$T4282800 <= 1960.0] <- 1900.0
  data$T4282800[2000.0 <= data$T4282800 & data$T4282800 <= 2060.0] <- 2000.0
  data$T4282800[2100.0 <= data$T4282800 & data$T4282800 <= 2150.0] <- 2100.0
  data$T4282800[2200.0 <= data$T4282800 & data$T4282800 <= 2340.0] <- 2200.0
  data$T4282800[2400.0 <= data$T4282800 & data$T4282800 <= 2550.0] <- 2400.0
  data$T4282800[2600.0 <= data$T4282800 & data$T4282800 <= 2760.0] <- 2600.0
  data$T4282800[2800.0 <= data$T4282800 & data$T4282800 <= 2960.0] <- 2800.0
  data$T4282800[3000.0 <= data$T4282800 & data$T4282800 <= 3260.0] <- 3000.0
  data$T4282800[3300.0 <= data$T4282800 & data$T4282800 <= 3650.0] <- 3300.0
  data$T4282800[3700.0 <= data$T4282800 & data$T4282800 <= 3950.0] <- 3700.0
  data$T4282800[4000.0 <= data$T4282800 & data$T4282800 <= 4160.0] <- 4000.0
  data$T4282800[4200.0 <= data$T4282800 & data$T4282800 <= 4250.0] <- 4200.0
  data$T4282800[4300.0 <= data$T4282800 & data$T4282800 <= 4430.0] <- 4300.0
  data$T4282800[4500.0 <= data$T4282800 & data$T4282800 <= 4650.0] <- 4500.0
  data$T4282800[4700.0 <= data$T4282800 & data$T4282800 <= 4960.0] <- 4700.0
  data$T4282800[5000.0 <= data$T4282800 & data$T4282800 <= 5930.0] <- 5000.0
  data$T4282800[6000.0 <= data$T4282800 & data$T4282800 <= 6130.0] <- 6000.0
  data$T4282800[6200.0 <= data$T4282800 & data$T4282800 <= 6940.0] <- 6200.0
  data$T4282800[7000.0 <= data$T4282800 & data$T4282800 <= 7620.0] <- 7000.0
  data$T4282800[7700.0 <= data$T4282800 & data$T4282800 <= 7750.0] <- 7700.0
  data$T4282800[7800.0 <= data$T4282800 & data$T4282800 <= 7850.0] <- 7800.0
  data$T4282800[7900.0 <= data$T4282800 & data$T4282800 <= 8960.0] <- 7900.0
  data$T4282800[9000.0 <= data$T4282800 & data$T4282800 <= 9750.0] <- 9000.0
  data$T4282800[9800.0 <= data$T4282800 & data$T4282800 <= 9830.0] <- 9800.0
  data$T4282800 <- factor(data$T4282800,
                          levels=c(10.0,500.0,1000.0,1300.0,1600.0,1800.0,1900.0,2000.0,2100.0,2200.0,2400.0,2600.0,2800.0,3000.0,3300.0,3700.0,4000.0,4200.0,4300.0,4460.0,4500.0,4700.0,5000.0,6000.0,6200.0,7000.0,7700.0,7800.0,7900.0,9000.0,9800.0,9840.0,9950.0,9990.0),
                          labels=c("10 TO 430: Executive, Administrative and Managerial Occupations",
                                   "500 TO 950: Management Related Occupations",
                                   "1000 TO 1240: Mathematical and Computer Scientists",
                                   "1300 TO 1560: Engineers, Architects, Surveyers, Engineering and Related Technicians",
                                   "1600 TO 1760: Physical Scientists",
                                   "1800 TO 1860: Social Scientists and Related Workers",
                                   "1900 TO 1960: Life, Physical and Social Science Technicians",
                                   "2000 TO 2060: Counselors, Sociala and Religious Workers",
                                   "2100 TO 2150: Lawyers, Judges and Legal Support Workers",
                                   "2200 TO 2340: Teachers",
                                   "2400 TO 2550: Education, Training and Library Workers",
                                   "2600 TO 2760: Entertainers and Performers, Sports and Related Workers",
                                   "2800 TO 2960: Media and Communications Workers",
                                   "3000 TO 3260: Health Diagnosing and Treating Practitioners",
                                   "3300 TO 3650: Health Care Technical and Support Occupations",
                                   "3700 TO 3950: Protective Service Occupations",
                                   "4000 TO 4160: Food Preparation and Serving Related Occupations",
                                   "4200 TO 4250: Cleaning and Building Service Occupations",
                                   "4300 TO 4430: Entertainment Attendants and Related Workers",
                                   "4460: Funeral Related Occupations",
                                   "4500 TO 4650: Personal Care and Service Workers",
                                   "4700 TO 4960: Sales and Related Workers",
                                   "5000 TO 5930: Office and Administrative Support Workers",
                                   "6000 TO 6130: Farming, Fishing and Forestry Occupations",
                                   "6200 TO 6940: Construction Trade and Extraction Workers",
                                   "7000 TO 7620: Installation, Maintenance and Repairs Workers",
                                   "7700 TO 7750: Production and Operating Workers",
                                   "7800 TO 7850: Food Preparation Occupations",
                                   "7900 TO 8960: Setters, Operators and Tenders",
                                   "9000 TO 9750: Transportation and Material Moving Workers",
                                   "9800 TO 9830: Military Specific Occupations",
                                   "9840: Armed Forces",
                                   "9950: Not in Labor Force (ACS Code)",
                                   "9990: Uncodeable"))
  data$T5256900[10.0 <= data$T5256900 & data$T5256900 <= 430.0] <- 10.0
  data$T5256900[500.0 <= data$T5256900 & data$T5256900 <= 950.0] <- 500.0
  data$T5256900[1000.0 <= data$T5256900 & data$T5256900 <= 1240.0] <- 1000.0
  data$T5256900[1300.0 <= data$T5256900 & data$T5256900 <= 1560.0] <- 1300.0
  data$T5256900[1600.0 <= data$T5256900 & data$T5256900 <= 1760.0] <- 1600.0
  data$T5256900[1800.0 <= data$T5256900 & data$T5256900 <= 1860.0] <- 1800.0
  data$T5256900[1900.0 <= data$T5256900 & data$T5256900 <= 1960.0] <- 1900.0
  data$T5256900[2000.0 <= data$T5256900 & data$T5256900 <= 2060.0] <- 2000.0
  data$T5256900[2100.0 <= data$T5256900 & data$T5256900 <= 2150.0] <- 2100.0
  data$T5256900[2200.0 <= data$T5256900 & data$T5256900 <= 2340.0] <- 2200.0
  data$T5256900[2400.0 <= data$T5256900 & data$T5256900 <= 2550.0] <- 2400.0
  data$T5256900[2600.0 <= data$T5256900 & data$T5256900 <= 2760.0] <- 2600.0
  data$T5256900[2800.0 <= data$T5256900 & data$T5256900 <= 2960.0] <- 2800.0
  data$T5256900[3000.0 <= data$T5256900 & data$T5256900 <= 3260.0] <- 3000.0
  data$T5256900[3300.0 <= data$T5256900 & data$T5256900 <= 3650.0] <- 3300.0
  data$T5256900[3700.0 <= data$T5256900 & data$T5256900 <= 3950.0] <- 3700.0
  data$T5256900[4000.0 <= data$T5256900 & data$T5256900 <= 4160.0] <- 4000.0
  data$T5256900[4200.0 <= data$T5256900 & data$T5256900 <= 4250.0] <- 4200.0
  data$T5256900[4300.0 <= data$T5256900 & data$T5256900 <= 4430.0] <- 4300.0
  data$T5256900[4500.0 <= data$T5256900 & data$T5256900 <= 4650.0] <- 4500.0
  data$T5256900[4700.0 <= data$T5256900 & data$T5256900 <= 4960.0] <- 4700.0
  data$T5256900[5000.0 <= data$T5256900 & data$T5256900 <= 5930.0] <- 5000.0
  data$T5256900[6000.0 <= data$T5256900 & data$T5256900 <= 6130.0] <- 6000.0
  data$T5256900[6200.0 <= data$T5256900 & data$T5256900 <= 6940.0] <- 6200.0
  data$T5256900[7000.0 <= data$T5256900 & data$T5256900 <= 7620.0] <- 7000.0
  data$T5256900[7700.0 <= data$T5256900 & data$T5256900 <= 7750.0] <- 7700.0
  data$T5256900[7800.0 <= data$T5256900 & data$T5256900 <= 7850.0] <- 7800.0
  data$T5256900[7900.0 <= data$T5256900 & data$T5256900 <= 8960.0] <- 7900.0
  data$T5256900[9000.0 <= data$T5256900 & data$T5256900 <= 9750.0] <- 9000.0
  data$T5256900[9800.0 <= data$T5256900 & data$T5256900 <= 9830.0] <- 9800.0
  data$T5256900 <- factor(data$T5256900,
                          levels=c(10.0,500.0,1000.0,1300.0,1600.0,1800.0,1900.0,2000.0,2100.0,2200.0,2400.0,2600.0,2800.0,3000.0,3300.0,3700.0,4000.0,4200.0,4300.0,4460.0,4500.0,4700.0,5000.0,6000.0,6200.0,7000.0,7700.0,7800.0,7900.0,9000.0,9800.0,9840.0,9950.0,9990.0),
                          labels=c("10 TO 430: Executive, Administrative and Managerial Occupations",
                                   "500 TO 950: Management Related Occupations",
                                   "1000 TO 1240: Mathematical and Computer Scientists",
                                   "1300 TO 1560: Engineers, Architects, Surveyers, Engineering and Related Technicians",
                                   "1600 TO 1760: Physical Scientists",
                                   "1800 TO 1860: Social Scientists and Related Workers",
                                   "1900 TO 1960: Life, Physical and Social Science Technicians",
                                   "2000 TO 2060: Counselors, Sociala and Religious Workers",
                                   "2100 TO 2150: Lawyers, Judges and Legal Support Workers",
                                   "2200 TO 2340: Teachers",
                                   "2400 TO 2550: Education, Training and Library Workers",
                                   "2600 TO 2760: Entertainers and Performers, Sports and Related Workers",
                                   "2800 TO 2960: Media and Communications Workers",
                                   "3000 TO 3260: Health Diagnosing and Treating Practitioners",
                                   "3300 TO 3650: Health Care Technical and Support Occupations",
                                   "3700 TO 3950: Protective Service Occupations",
                                   "4000 TO 4160: Food Preparation and Serving Related Occupations",
                                   "4200 TO 4250: Cleaning and Building Service Occupations",
                                   "4300 TO 4430: Entertainment Attendants and Related Workers",
                                   "4460: Funeral Related Occupations",
                                   "4500 TO 4650: Personal Care and Service Workers",
                                   "4700 TO 4960: Sales and Related Workers",
                                   "5000 TO 5930: Office and Administrative Support Workers",
                                   "6000 TO 6130: Farming, Fishing and Forestry Occupations",
                                   "6200 TO 6940: Construction Trade and Extraction Workers",
                                   "7000 TO 7620: Installation, Maintenance and Repairs Workers",
                                   "7700 TO 7750: Production and Operating Workers",
                                   "7800 TO 7850: Food Preparation Occupations",
                                   "7900 TO 8960: Setters, Operators and Tenders",
                                   "9000 TO 9750: Transportation and Material Moving Workers",
                                   "9800 TO 9830: Military Specific Occupations",
                                   "9840: Armed Forces",
                                   "9950: Not in Labor Force (ACS Code)",
                                   "9990: Uncodeable"))
  data$T7818600[10.0 <= data$T7818600 & data$T7818600 <= 430.0] <- 10.0
  data$T7818600[500.0 <= data$T7818600 & data$T7818600 <= 950.0] <- 500.0
  data$T7818600[1000.0 <= data$T7818600 & data$T7818600 <= 1240.0] <- 1000.0
  data$T7818600[1300.0 <= data$T7818600 & data$T7818600 <= 1560.0] <- 1300.0
  data$T7818600[1600.0 <= data$T7818600 & data$T7818600 <= 1760.0] <- 1600.0
  data$T7818600[1800.0 <= data$T7818600 & data$T7818600 <= 1860.0] <- 1800.0
  data$T7818600[1900.0 <= data$T7818600 & data$T7818600 <= 1960.0] <- 1900.0
  data$T7818600[2000.0 <= data$T7818600 & data$T7818600 <= 2060.0] <- 2000.0
  data$T7818600[2100.0 <= data$T7818600 & data$T7818600 <= 2150.0] <- 2100.0
  data$T7818600[2200.0 <= data$T7818600 & data$T7818600 <= 2340.0] <- 2200.0
  data$T7818600[2400.0 <= data$T7818600 & data$T7818600 <= 2550.0] <- 2400.0
  data$T7818600[2600.0 <= data$T7818600 & data$T7818600 <= 2760.0] <- 2600.0
  data$T7818600[2800.0 <= data$T7818600 & data$T7818600 <= 2960.0] <- 2800.0
  data$T7818600[3000.0 <= data$T7818600 & data$T7818600 <= 3260.0] <- 3000.0
  data$T7818600[3300.0 <= data$T7818600 & data$T7818600 <= 3650.0] <- 3300.0
  data$T7818600[3700.0 <= data$T7818600 & data$T7818600 <= 3950.0] <- 3700.0
  data$T7818600[4000.0 <= data$T7818600 & data$T7818600 <= 4160.0] <- 4000.0
  data$T7818600[4200.0 <= data$T7818600 & data$T7818600 <= 4250.0] <- 4200.0
  data$T7818600[4300.0 <= data$T7818600 & data$T7818600 <= 4430.0] <- 4300.0
  data$T7818600[4500.0 <= data$T7818600 & data$T7818600 <= 4650.0] <- 4500.0
  data$T7818600[4700.0 <= data$T7818600 & data$T7818600 <= 4960.0] <- 4700.0
  data$T7818600[5000.0 <= data$T7818600 & data$T7818600 <= 5930.0] <- 5000.0
  data$T7818600[6000.0 <= data$T7818600 & data$T7818600 <= 6130.0] <- 6000.0
  data$T7818600[6200.0 <= data$T7818600 & data$T7818600 <= 6940.0] <- 6200.0
  data$T7818600[7000.0 <= data$T7818600 & data$T7818600 <= 7620.0] <- 7000.0
  data$T7818600[7700.0 <= data$T7818600 & data$T7818600 <= 7750.0] <- 7700.0
  data$T7818600[7800.0 <= data$T7818600 & data$T7818600 <= 7850.0] <- 7800.0
  data$T7818600[7900.0 <= data$T7818600 & data$T7818600 <= 8960.0] <- 7900.0
  data$T7818600[9000.0 <= data$T7818600 & data$T7818600 <= 9750.0] <- 9000.0
  data$T7818600[9800.0 <= data$T7818600 & data$T7818600 <= 9830.0] <- 9800.0
  data$T7818600 <- factor(data$T7818600,
                          levels=c(10.0,500.0,1000.0,1300.0,1600.0,1800.0,1900.0,2000.0,2100.0,2200.0,2400.0,2600.0,2800.0,3000.0,3300.0,3700.0,4000.0,4200.0,4300.0,4460.0,4500.0,4700.0,5000.0,6000.0,6200.0,7000.0,7700.0,7800.0,7900.0,9000.0,9800.0,9840.0,9950.0,9990.0),
                          labels=c("10 TO 430: Executive, Administrative and Managerial Occupations",
                                   "500 TO 950: Management Related Occupations",
                                   "1000 TO 1240: Mathematical and Computer Scientists",
                                   "1300 TO 1560: Engineers, Architects, Surveyers, Engineering and Related Technicians",
                                   "1600 TO 1760: Physical Scientists",
                                   "1800 TO 1860: Social Scientists and Related Workers",
                                   "1900 TO 1960: Life, Physical and Social Science Technicians",
                                   "2000 TO 2060: Counselors, Sociala and Religious Workers",
                                   "2100 TO 2150: Lawyers, Judges and Legal Support Workers",
                                   "2200 TO 2340: Teachers",
                                   "2400 TO 2550: Education, Training and Library Workers",
                                   "2600 TO 2760: Entertainers and Performers, Sports and Related Workers",
                                   "2800 TO 2960: Media and Communications Workers",
                                   "3000 TO 3260: Health Diagnosing and Treating Practitioners",
                                   "3300 TO 3650: Health Care Technical and Support Occupations",
                                   "3700 TO 3950: Protective Service Occupations",
                                   "4000 TO 4160: Food Preparation and Serving Related Occupations",
                                   "4200 TO 4250: Cleaning and Building Service Occupations",
                                   "4300 TO 4430: Entertainment Attendants and Related Workers",
                                   "4460: Funeral Related Occupations",
                                   "4500 TO 4650: Personal Care and Service Workers",
                                   "4700 TO 4960: Sales and Related Workers",
                                   "5000 TO 5930: Office and Administrative Support Workers",
                                   "6000 TO 6130: Farming, Fishing and Forestry Occupations",
                                   "6200 TO 6940: Construction Trade and Extraction Workers",
                                   "7000 TO 7620: Installation, Maintenance and Repairs Workers",
                                   "7700 TO 7750: Production and Operating Workers",
                                   "7800 TO 7850: Food Preparation Occupations",
                                   "7900 TO 8960: Setters, Operators and Tenders",
                                   "9000 TO 9750: Transportation and Material Moving Workers",
                                   "9800 TO 9830: Military Specific Occupations",
                                   "9840: Armed Forces",
                                   "9950: Not in Labor Force (ACS Code)",
                                   "9990: Uncodeable"))
  return(data)
}

varlabels <- c("ID# (1-12686) 79",
               "OCC @ CUR/M-RCNT JOB 70 3D CP79",
               "SAMPLE ID  79 INT",
               "RACL/ETHNIC COHORT /SCRNR 79",
               "SEX OF R 79",
               "OCC @ CUR/M-RCNT JOB 70 3D CP80",
               "OCC @ CUR/M-RCNT JOB 70 3D CP81",
               "OCC @ CUR/M-RCNT JOB 70 3D CP82",
               "OCC @ CUR/M-RCNT JOB 70 3D CP83",
               "OCC @ CUR/M-RCNT JOB 70 3D CP84",
               "OCC @ CUR/M-RCNT JOB 70 3D CP85",
               "OCC @ CUR/M-RCNT JOB 70 3D CP86",
               "OCC @ CUR/M-RCNT JOB 70 3D CP87",
               "OCC @ CUR/M-RCNT JOB 70 3D CP88",
               "OCC @ CUR/M-RCNT JOB 70 3D CP89",
               "OCC @ CUR/M-RCNT JOB 70 3D CP90",
               "OCC @ CUR/M-RCNT JOB 70 3D CP91",
               "OCC @ CUR/M-RCNT JOB 70 3D CP92",
               "TYPE OF OCCUPATION DOING LAST WK 93",
               "OCCUPATION (70 CODES) ALL JOB #1 94",
               "OCCUPATION (70 CODES) ALL JOB #1 96",
               "OCCUPATION (70 CODES) ALL JOB L1 1998",
               "OCCUPATION (70 CODES) ALL JOB L1 2000",
               "OCCUPATION (2000 CODES) ALL JOB L1 2002",
               "OCCUPATION (2000 CODES) ALL JOB L1 2004",
               "OCCUPATION (2000 CODES) ALL JOB L1 2006",
               "OCCUPATION (2000 CODES) ALL JOB L1 2008",
               "OCCUPATION (2000 CODES) ALL JOB L1 2010",
               "OCCUPATION (2000 CODES) ALL JOB L1 2012",
               "OCCUPATION (2000 CODES) ALL JOB L1 2014",
               "OCCUPATION (2000 CODES) ALL JOB L1 2016",
               "OCCUPATION (2000 CODES) ALL JOB L1 2018"
)


# Use qnames rather than rnums

qnames = function(data) {
  names(data) <- c("CASEID_1979",
                   "CPSOCC70_1979",
                   "SAMPLE_ID_1979",
                   "SAMPLE_RACE_78SCRN",
                   "SAMPLE_SEX_1979",
                   "CPSOCC70_1980",
                   "CPSOCC70_1981",
                   "CPSOCC70_1982",
                   "CPSOCC70_1983",
                   "CPSOCC70_1984",
                   "CPSOCC70_1985",
                   "CPSOCC70_1986",
                   "CPSOCC70_1987",
                   "CPSOCC70_1988",
                   "CPSOCC70_1989",
                   "CPSOCC70_1990",
                   "CPSOCC70_1991",
                   "CPSOCC70_1992",
                   "CPSOCC70_1993",
                   "OCCALL-EMP.01_1994",
                   "OCCALL-EMP.01_1996",
                   "OCCALL-EMP.01_1998",
                   "OCCALL-EMP.01_2000",
                   "OCCALL-EMP.01_2002",
                   "OCCALL-EMP.01_2004",
                   "OCCALL-EMP.01_2006",
                   "OCCALL-EMP.01_2008",
                   "OCCALL-EMP.01_2010",
                   "OCCALL-EMP.01_2012",
                   "OCCALL-EMP.01_2014",
                   "OCCALL-EMP.01_2016",
                   "OCCALL-EMP.01_2018")
  return(data)
}

# Final dataset
occupations <- qnames(new_data)
